import { GoogleGenAI } from "@google/genai";

const getClient = () => {
  const apiKey = process.env.API_KEY;
  if (!apiKey) {
    throw new Error("API Key not found");
  }
  return new GoogleGenAI({ apiKey });
};

type EnhanceAction = 'REMOVE_BG' | 'ENHANCE' | 'BOTH';

export const enhancePhoto = async (base64Image: string, action: EnhanceAction = 'BOTH'): Promise<string> => {
  const ai = getClient();
  
  // Strip the prefix for the API call
  const cleanBase64 = base64Image.replace(/^data:image\/(png|jpeg|jpg|webp);base64,/, '');

  let prompt = "";
  switch(action) {
    case 'REMOVE_BG':
      prompt = "Strictly remove the background of this image and replace it with a clean, solid white background. Do NOT change the person's face, lighting or details. Just swap the background for white. Return ONLY the image.";
      break;
    case 'ENHANCE':
      prompt = "Improve the image quality, sharpness, and lighting of this ID photo to look professional. Reduce noise and fix blur. Do NOT change the background content, keep it as is (or white if it is already white). Return ONLY the image.";
      break;
    case 'BOTH':
    default:
      prompt = "Optimize this image for a formal ID card (3x4 format). 1. Remove the background and replace it with a clean, flat white background. 2. Improve the lighting on the face to be even and professional. 3. Enhance sharpness slightly. Return ONLY the image.";
      break;
  }

  try {
    const response = await ai.models.generateContent({
      model: 'gemini-2.5-flash-image',
      contents: {
        parts: [
          { text: prompt },
          {
            inlineData: {
              mimeType: 'image/jpeg',
              data: cleanBase64
            }
          }
        ]
      }
    });

    if (response.candidates?.[0]?.content?.parts) {
      for (const part of response.candidates[0].content.parts) {
        if (part.inlineData && part.inlineData.data) {
          return `data:image/png;base64,${part.inlineData.data}`;
        }
      }
    }
    
    throw new Error("No image generated by AI");
  } catch (error) {
    console.error("Gemini API Error:", error);
    throw error;
  }
};

export const generateSuitPhoto = async (base64Image: string, suitDescription: string): Promise<string> => {
  const ai = getClient();
  const cleanBase64 = base64Image.replace(/^data:image\/(png|jpeg|jpg|webp);base64,/, '');

  const prompt = `Edite esta foto para um documento oficial 3x4.
  AÇÃO: Vista a pessoa da foto com um traje formal: "${suitDescription}".
  REGRAS CRÍTICAS:
  1. A cabeça, rosto, cabelo e expressão facial devem permanecer 100% IDÊNTICOS aos originais. Não altere a identidade.
  2. O terno deve ser ajustado perfeitamente ao corpo, com caimento natural nos ombros e pescoço.
  3. O fundo deve ser substituído por BRANCO SÓLIDO (#FFFFFF).
  4. A iluminação do terno deve ser consistente com a do rosto.
  5. Remova qualquer roupa anterior que possa estar visível.
  6. Retorne APENAS a imagem final.`;

  try {
    const response = await ai.models.generateContent({
      model: 'gemini-2.5-flash-image',
      contents: {
        parts: [
          { text: prompt },
          {
            inlineData: {
              mimeType: 'image/jpeg',
              data: cleanBase64
            }
          }
        ]
      }
    });

    if (response.candidates?.[0]?.content?.parts) {
      for (const part of response.candidates[0].content.parts) {
        if (part.inlineData && part.inlineData.data) {
          return `data:image/png;base64,${part.inlineData.data}`;
        }
      }
    }
    
    throw new Error("No image generated by AI");
  } catch (error) {
    console.error("Gemini Suit Gen Error:", error);
    throw error;
  }
};