import { GoogleGenAI } from "@google/genai";

const getClient = () => {
  const apiKey = process.env.API_KEY;
  if (!apiKey) {
    throw new Error("API Key not found");
  }
  return new GoogleGenAI({ apiKey });
};

type EnhanceAction = 'REMOVE_BG' | 'ENHANCE' | 'BOTH';

export const enhancePhoto = async (base64Image: string, action: EnhanceAction = 'BOTH'): Promise<string> => {
  const ai = getClient();
  
  // Strip the prefix for the API call
  const cleanBase64 = base64Image.replace(/^data:image\/(png|jpeg|jpg|webp);base64,/, '');

  let prompt = "";
  switch(action) {
    case 'REMOVE_BG':
      prompt = "Strictly remove the background of this image and replace it with a clean, solid white background. Do NOT change the person's face, lighting or details. Just swap the background for white. Return ONLY the image.";
      break;
    case 'ENHANCE':
      prompt = "Improve the image quality, sharpness, and lighting of this ID photo to look professional. Reduce noise and fix blur. Do NOT change the background content, keep it as is (or white if it is already white). Return ONLY the image.";
      break;
    case 'BOTH':
    default:
      prompt = "Optimize this image for a formal ID card (3x4 format). 1. Remove the background and replace it with a clean, flat white background. 2. Improve the lighting on the face to be even and professional. 3. Enhance sharpness slightly. Return ONLY the image.";
      break;
  }

  try {
    const response = await ai.models.generateContent({
      model: 'gemini-2.5-flash-image',
      contents: {
        parts: [
          { text: prompt },
          {
            inlineData: {
              mimeType: 'image/jpeg',
              data: cleanBase64
            }
          }
        ]
      }
    });

    if (response.candidates?.[0]?.content?.parts) {
      for (const part of response.candidates[0].content.parts) {
        if (part.inlineData && part.inlineData.data) {
          return `data:image/png;base64,${part.inlineData.data}`;
        }
      }
    }
    
    throw new Error("No image generated by AI");
  } catch (error) {
    console.error("Gemini API Error:", error);
    throw error;
  }
};